# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: daily
    target-branch: main

  - directory: /.github/workflows
    package-ecosystem: github-actions
    schedule:
      interval: daily
    target-branch: main
