name: Go Test

on:
  push:
    paths:
      - "!.github/"
      - "!.gitignore"
      - "!**.md"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/unit-test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test -v ./...