# Copyright 2023 UMH Systems GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: golint
on:
  push:
    paths:
      - '!.github/**'
      - '.github/workflows/golint.yaml'
      - '!.gitignore'
      - '!README.md'

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  lint-and-check:
    name: Lint and Check Go code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.*'
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck and generate report
        run: govulncheck ./...
        shell: bash
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v