name: Release

on:
  workflow_run:
    workflows: ["Go Test"]
    branches: ["main"]
    types:
      - completed

jobs:

  release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref_type == 'tag' &&
      startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true